[package]
name = "rustygrad-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
impl_ops = "0.1.1"
uuid = { version = "1.3.0", features = ["v4"] }
